
name: Modified CI
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version:
        - 8
      max-parallel: 4
    name: test (${{ matrix.java_version }})
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test (${{ matrix.java_version }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/jsonschema2pojo/jsonschema2pojo', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.14.0
      with:
        checkout-fetch-depth: 0
        java-version: ${{ matrix.java_version }}
        java-distribution: temurin
        maven-version: 3.8.7
    - run: touch optcd-3.txt
    - name: Verify with Maven
      run: mvn verify -B
    - run: touch optcd-4.txt
    - name: Verify jsonschema2pojo-gradle-plugin integration tests
      run: |-
        mvn -U -B install -DskipTests -Dmaven.javadoc.skip -Dmaven.site.skip -pl jsonschema2pojo-gradle-plugin -am
        mvn -U -B install -pl jsonschema2pojo-gradle-plugin
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test (${{ matrix.java_version }})
        path: /home/runner/inotifywait-log-test (${{ matrix.java_version }}).csv
'on':
- push
- workflow_dispatch
